import { Inter } from 'next/font/google';
import { GlobalContextProvider } from '@/context/store';
const inter = Inter({ subsets: ['latin'] });
import React from 'react';
import '../styles/global.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'PortalAdm',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
