'use client';
import { Inter } from 'next/font/google';
import { GlobalContextProvider } from '@/context/store';
const inter = Inter({ subsets: ['latin'] });

import { ReactNode } from 'react';
export const metadata = {
  title: 'Beyond V2',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
